Create azure-webapps-node.yml
UB-ES-2023-F1/GoPodcastWEB pull request #3
Opened 2023-10-08 11:46 UTC by Mikolsito

2023-10-08 11:47 UTC, Mikolsito commented
Falta omplir els camps amb les dades d'Azure. S'hauria d'haver enviat permís a l'Eloi perquè doni accés a Azure per llegir les dades de l'organització. Sense això no puc omplir els camps necessaris per fer la connexió des d'Azure

2023-10-10 13:39 UTC, chuancho22 commented
M'espero doncs a conseguir el permís de azure i que facis les probes per acceptar-ho.

2023-10-10 13:41 UTC, chuancho22 requested changes
Ho poso com a 'request changes' per tal d'esperar a les dades i proves del tema d'Azure.

2023-10-16 19:24 UTC, Mikolsito commented
Tanco aquesta PR perquè ja vaig fer els canvis que tocaven

2023-10-16 19:24 UTC, closed without merging